version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:20
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Build project
          command: npm run build

      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud