version: 2.1

jobs:
  validate:
    docker:
      - image: cimg/node:22.11

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-

      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          paths:
            - ~/.npm
          key: v1-npm-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Run Tests
          command: npm run test

      - run:
          name: Run Lint checks
          command: npm run lint

      - run:
          name: Run Production Build
          command: npm run build

      - run:
          name: SonarCloud Scan
          command: npx sonar-scanner

workflows:
  version: 2
  validate_project:
    jobs:
      - validate:
          context: SonarCloud