version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  validate:
    docker:
      - image: cimg/node:22.11

    steps:
      - checkout

      - run:
          name: Fetch full git history
          command: |
            git fetch --prune --unshallow || true
            git fetch --all

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run tests
          command: npm run test

      - run:
          name: Run lint
          command: npm run lint

      - run:
          name: Build project
          command: npm run build

      - sonarcloud/scan

workflows:
  validate_project:
    jobs:
      - validate:
          context: SonarCloud