import { NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY } from "@/config/env.public";

export const SUPABASE_URL = NEXT_PUBLIC_SUPABASE_URL;
export const SUPABASE_ANON_KEY = NEXT_PUBLIC_SUPABASE_ANON_KEY;